version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Next.js
      - "1337:1337" # Strapi
    environment:
      - NODE_ENV=production
    volumes:
      - app_data:/app/strapi/public/uploads
    restart: unless-stopped

volumes:
  app_data:
